import mongoose from "mongoose";
import Complaint from "../models/Complaint.js";
import Notification from "../models/Notification.js";
import asyncHandler from "../utils/asyncHandler.js";
import {
  analyzeWasteComplaint,
  analyzeWasteImage,
  buildCleanlinessVerification,
} from "../utils/aiWasteAnalysis.js";
import {
  createOfflineComplaint,
  getOfflineComplaintById,
  getOfflineComplaints,
  updateOfflineComplaint,
} from "../utils/offlineComplaintStore.js";
import { isDatabaseAuthError } from "../utils/offlineAuthStore.js";

const buildTimeline = () => [
  {
    label: "Submitted",
    detail: "Complaint captured with image, location, and timestamp.",
    status: "complete",
  },
  {
    label: "AI Verification",
    detail: "Waste type, severity, and confidence generated by EcoPulse AI.",
    status: "complete",
  },
  {
    label: "Worker Assignment",
    detail: "Waiting for the assigned worker to accept the task.",
    status: "active",
  },
  {
    label: "Cleaning",
    detail: "Before/after proof will be verified after cleanup.",
    status: "pending",
  },
];

export const analyzeComplaintImage = asyncHandler(async (req, res) => {
  const { image, filename, location, description } = req.body;

  if (!image) {
    res.status(400);
    throw new Error("Image is required for analysis");
  }

  const analysis = await analyzeWasteImage({ image, filename, location, description });

  res.json({
    success: true,
    analysis,
  });
});

export const createComplaint = asyncHandler(async (req, res) => {
  const { image, location, description, category, priority } = req.body;

  if (!location || !category) {
    res.status(400);
    throw new Error("Location and category are required");
  }

  if (mongoose.connection.readyState !== 1) {
    const complaint = await createOfflineComplaint({ user: req.user, payload: req.body });

    res.status(201).json({
      success: true,
      complaint,
    });
    return;
  }

  const aiAnalysis = analyzeWasteComplaint({ category, description, priority });

  let complaint;

  try {
    complaint = await Complaint.create({
      citizen: req.user._id,
      image,
      location,
      description,
      category: aiAnalysis.category || category,
      priority: priority || aiAnalysis.severity,
      status: "Submitted",
      aiAnalysis,
      timeline: buildTimeline(),
    });

    await Notification.create({
      user: req.user._id,
      title: "Complaint submitted",
      message: `${complaint.complaintId} is verified by EcoPulse AI and waiting for worker assignment.`,
      type: "complaint",
    });
  } catch (error) {
    if (!isDatabaseAuthError(error)) {
      throw error;
    }

    complaint = await createOfflineComplaint({ user: req.user, payload: req.body });
  }

  res.status(201).json({
    success: true,
    complaint,
  });
});

export const getComplaints = asyncHandler(async (req, res) => {
  if (mongoose.connection.readyState !== 1) {
    const complaints = await getOfflineComplaints(req.user);

    res.json({
      success: true,
      complaints,
    });
    return;
  }

  const filter = req.user.role === "citizen" ? { citizen: req.user._id } : {};
  let complaints;

  try {
    complaints = await Complaint.find(filter).sort({ createdAt: -1 });
  } catch (error) {
    if (!isDatabaseAuthError(error)) {
      throw error;
    }

    complaints = await getOfflineComplaints(req.user);
  }

  res.json({
    success: true,
    complaints,
  });
});

export const getComplaintById = asyncHandler(async (req, res) => {
  let complaint;

  if (mongoose.connection.readyState !== 1) {
    complaint = await getOfflineComplaintById({ id: req.params.id, user: req.user });
  } else {
    try {
      complaint = await Complaint.findOne({
        $or: [{ _id: req.params.id }, { complaintId: req.params.id }],
      });
    } catch (error) {
      if (!isDatabaseAuthError(error)) {
        throw error;
      }

      complaint = await getOfflineComplaintById({ id: req.params.id, user: req.user });
    }
  }

  if (!complaint) {
    res.status(404);
    throw new Error("Complaint not found");
  }

  if (
    req.user.role === "citizen" &&
    complaint.citizen.toString() !== req.user._id.toString()
  ) {
    res.status(403);
    throw new Error("You can only view your own complaints");
  }

  res.json({
    success: true,
    complaint,
  });
});

export const updateComplaintStatus = asyncHandler(async (req, res) => {
  let complaint;

  if (mongoose.connection.readyState !== 1) {
    complaint = await updateOfflineComplaint({ id: req.params.id, payload: req.body });

    if (!complaint) {
      res.status(404);
      throw new Error("Complaint not found");
    }

    res.json({
      success: true,
      complaint,
    });
    return;
  }

  try {
    complaint = await Complaint.findOne({
      $or: [{ _id: req.params.id }, { complaintId: req.params.id }],
    });
  } catch (error) {
    if (!isDatabaseAuthError(error)) {
      throw error;
    }

    complaint = await updateOfflineComplaint({ id: req.params.id, payload: req.body });

    if (!complaint) {
      res.status(404);
      throw new Error("Complaint not found");
    }

    res.json({
      success: true,
      complaint,
    });
    return;
  }

  if (!complaint) {
    res.status(404);
    throw new Error("Complaint not found");
  }

  if (req.body.ignore) {
    complaint.ignoreCount = (complaint.ignoreCount || 0) + 1;
    complaint.status = complaint.ignoreCount >= 3 ? "Escalated" : "No response";
    complaint.timeline.push({
      label: "Ignored by worker",
      detail: `Task ignored by assigned worker. Reminder ${complaint.ignoreCount} sent.`,
      status: "active",
    });

    if (complaint.ignoreCount >= 3 && !complaint.escalated) {
      complaint.escalated = true;
      complaint.escalationReason = "Repeated ignore by worker";
      complaint.timeline.push({
        label: "Escalated",
        detail: "Forwarded to supervisor due to repeated ignores.",
        status: "active",
      });

      await Notification.create({
        user: null,
        title: `Escalation: ${complaint.complaintId}`,
        message: `Complaint ${complaint.complaintId} has been escalated after ${complaint.ignoreCount} ignored task attempts.`,
        type: "system",
      });
    } else {
      await Notification.create({
        user: null,
        title: `Reminder: ${complaint.complaintId}`,
        message: `Worker reminder generated for ${complaint.complaintId}. Ignore count ${complaint.ignoreCount}.`,
        type: "assignment",
      });
    }

    await complaint.save();

    res.json({
      success: true,
      complaint,
    });
    return;
  }

  complaint.status = req.body.status || complaint.status;

  if (req.body.beforeImage || req.body.afterImage) {
    complaint.beforeImage = req.body.beforeImage || complaint.beforeImage;
    complaint.afterImage = req.body.afterImage || complaint.afterImage;
    const verification = await buildCleanlinessVerification(complaint);
    complaint.cleaningVerification = verification;
    complaint.timeline.push({
      label: "AI Cleaning Verification",
      detail: `${verification.result} with ${verification.confidence}% confidence.`,
      status: verification.result === "Clean" ? "complete" : "active",
    });

    // If verification passed, mark complaint completed and update previous 'Cleaning' timeline step
    if (verification.result === "Clean") {
      complaint.status = "Completed";
      // mark any existing 'Cleaning' timeline entry as complete
      complaint.timeline = complaint.timeline.map((t) =>
        /clean/i.test(t.label) ? { ...t, status: "complete" } : t
      );
    }
  }

  // If status explicitly set to Completed (e.g., citizen marked resolved), update timeline accordingly
  if (req.body.status === "Completed") {
    // mark cleaning and worker assignment steps as complete
    complaint.timeline = complaint.timeline.map((t) => {
      if (/clean|worker assignment/i.test(t.label)) return { ...t, status: "complete" };
      return t;
    });

    // add a Completed/Resolved entry if not present
    if (!complaint.timeline.some((t) => /completed|resolved/i.test(t.label))) {
      complaint.timeline.push({
        label: "Completed",
        detail: "Complaint marked completed.",
        status: "complete",
      });
    }
  }

  await complaint.save();

  res.json({
    success: true,
    complaint,
  });
});

export const getComplaintDashboard = asyncHandler(async (req, res) => {
  const filter = req.user.role === "citizen" ? { citizen: req.user._id } : {};
  let complaints;

  if (mongoose.connection.readyState !== 1) {
    complaints = await getOfflineComplaints(req.user);
  } else {
    try {
      complaints = await Complaint.find(filter).sort({ createdAt: -1 });
    } catch (error) {
      if (!isDatabaseAuthError(error)) {
        throw error;
      }

      complaints = await getOfflineComplaints(req.user);
    }
  }
  const total = complaints.length;
  const resolved = complaints.filter((item) => item.status === "Completed").length;
  const pending = complaints.filter((item) => item.status !== "Completed").length;
  const highPriority = complaints.filter((item) => item.priority === "High").length;

  res.json({
    success: true,
    analytics: {
      total,
      resolved,
      pending,
      highPriority,
      carbonSaved: `${Math.max(resolved * 6, 24)} kg`,
      ecoScore: Math.min(72 + resolved * 3, 99),
      greenPoints: total * 120 + resolved * 80,
      currentRank: total > 5 ? "#7" : "#18",
    },
    recent: complaints.slice(0, 5),
  });
});
