import crypto from "crypto";
import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";
import { analyzeWasteComplaint, buildCleanlinessVerification } from "./aiWasteAnalysis.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const dataDir = path.resolve(__dirname, "..", "data");
const storePath = path.join(dataDir, "offline-complaints.json");

const readComplaints = async () => {
  try {
    const raw = await fs.readFile(storePath, "utf8");
    return JSON.parse(raw);
  } catch {
    return [];
  }
};

const writeComplaints = async (complaints) => {
  await fs.mkdir(dataDir, { recursive: true });
  await fs.writeFile(storePath, JSON.stringify(complaints, null, 2));
};

const buildTimeline = () => [
  {
    label: "Submitted",
    detail: "Complaint captured with image, location, and timestamp.",
    status: "complete",
  },
  {
    label: "AI Verification",
    detail: "Waste type, severity, and confidence generated by EcoPulse AI.",
    status: "complete",
  },
  {
    label: "Worker Assignment",
    detail: "Waiting for the assigned worker to accept the task.",
    status: "active",
  },
  {
    label: "Cleaning",
    detail: "Before/after proof will be verified after cleanup.",
    status: "pending",
  },
];

const nextComplaintId = (complaints) => {
  const maxNumber = complaints.reduce((max, complaint) => {
    const number = Number(String(complaint.complaintId || "").replace("CP-", ""));
    return Number.isFinite(number) ? Math.max(max, number) : max;
  }, 1023);

  return `CP-${String(maxNumber + 1).padStart(4, "0")}`;
};

const sortNewestFirst = (complaints) =>
  [...complaints].sort(
    (a, b) => new Date(b.updatedAt || b.createdAt) - new Date(a.updatedAt || a.createdAt)
  );

export const createOfflineComplaint = async ({ user, payload }) => {
  const complaints = await readComplaints();
  const { image, location, description, category, priority } = payload;
  const now = new Date().toISOString();
  const aiAnalysis = analyzeWasteComplaint({ category, description, priority });
  const complaint = {
    _id: crypto.randomUUID(),
    complaintId: nextComplaintId(complaints),
    citizen: user._id || user.id,
    assignedWorker: {
      name: "Worker Team B",
      phone: "+91 9876543210",
    },
    assignedArea: "Kukatpally Zone",
    estimatedResponseTime: "30-45 minutes",
    image,
    beforeImage: "",
    afterImage: "",
    cleaningVerification: null,
    location,
    description,
    category: aiAnalysis.category || category,
    priority: priority || aiAnalysis.severity,
    status: "Assigned",
    aiAnalysis,
    timeline: buildTimeline(),
    createdAt: now,
    updatedAt: now,
  };

  complaints.push(complaint);
  await writeComplaints(complaints);
  return complaint;
};

export const getOfflineComplaints = async (user) => {
  const complaints = await readComplaints();
  const filtered =
    user.role === "citizen"
      ? complaints.filter((complaint) => complaint.citizen === (user._id || user.id))
      : complaints;

  return sortNewestFirst(filtered);
};

export const getOfflineComplaintById = async ({ id, user }) => {
  const complaints = await readComplaints();
  const complaint = complaints.find((item) => item._id === id || item.complaintId === id);

  if (!complaint) {
    return null;
  }

  if (user.role === "citizen" && complaint.citizen !== (user._id || user.id)) {
    const error = new Error("You can only view your own complaints");
    error.statusCode = 403;
    throw error;
  }

  return complaint;
};

export const updateOfflineComplaint = async ({ id, payload }) => {
  const complaints = await readComplaints();
  const index = complaints.findIndex((item) => item._id === id || item.complaintId === id);

  if (index === -1) {
    return null;
  }

  const complaint = {
    ...complaints[index],
    status: payload.status || complaints[index].status,
    beforeImage: payload.beforeImage || complaints[index].beforeImage,
    afterImage: payload.afterImage || complaints[index].afterImage,
    updatedAt: new Date().toISOString(),
  };

  if (payload.beforeImage || payload.afterImage) {
    const verification = await buildCleanlinessVerification(complaint);
    complaint.cleaningVerification = verification;
    complaint.timeline = [
      ...(complaint.timeline || []),
      {
        label: "AI Cleaning Verification",
        detail: `${verification.result} with ${verification.confidence}% confidence.`,
        status: verification.result === "Clean" ? "complete" : "active",
      },
    ];

    if (verification.result === "Clean") {
      complaint.status = "Completed";
    }
  }

  complaints[index] = complaint;
  await writeComplaints(complaints);
  return complaint;
};
